# version: 2.1
# jobs:
#   working_directory: ~/01/laravel-project
#   build:
#     docker:
#       - image: circleci/php:8.0-node-browsers
#     steps:
#       - checkout
#       - run: sudo composer self-update 
#       - run: composer install -n --prefer-dist
#       - run: npm ci
#       - run: npm run dev
#       - run:
#           name: php test
#           command: vendor/bin/phpunit

version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
<<<<<<< HEAD
      - checkout
      - run: sudo composer self-update 
      - run: composer install -n --prefer-dist --working-dir=./laravel-project
      # - run: npm ci --working-dir=./laravel-project
      # - run: npm run dev --working-dir=./laravel-project
      - run:
          command: php ./laravel-project/vendor/bin/phpunit --configuration=./laravel-project/phpunit.xml
      # - run: ls
=======
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  my-workflow:
    jobs:
      - hello-job
>>>>>>> 6c8f2e2... hello world
