version: 2.1
jobs:
  working_directory: ~/01/laravel-project
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update 
      - run: composer install -n --prefer-dist --working-dir=./laravel-project
      # - run: npm ci --working-dir=./laravel-project
      # - run: npm run dev --working-dir=./laravel-project
      - run:
          command: ./laravel-project/
          command: vendor/bin/phpunit
      # - run: ls
