version: 2.0
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update 
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit